const FALLEN_SOLDIERS = [
  {
    firstName: "יאסר",
    lastName: "אבו זידאן",
    age: 26,
  },
  {
    firstName: "סובחי",
    lastName: "אבו חמד",
    age: 43,
  },
  {
    firstName: "גאלב (מוניר)",
    lastName: "אבו מנסור",
    age: 32,
  },
  {
    firstName: "נוהד",
    lastName: "אבו רוקון",
    age: 38,
  },
  {
    firstName: "עאמד (סאמר)",
    lastName: "אבו ריש",
    age: 35,
    year: 1999,
  },
  {
    firstName: "אמציה-יהודה",
    lastName: "אבודרם",
    age: 22,
  },
  {
    firstName: "ניסים",
    lastName: "אביטן",
    age: 19,
  },
  {
    firstName: "אסף (אסי)",
    lastName: "אבני",
    age: 20,
  },
  {
    firstName: "חיים-מאיר",
    lastName: "אבנר",
    age: 28,
  },
  {
    firstName: "אבי-משה",
    lastName: "אבקסיס",
    age: 20,
  },
  {
    firstName: "שי",
    lastName: "אבקסיס",
    age: 22,
    year: 1997,
  },
  {
    firstName: "נחום-אורי",
    lastName: "אברהם",
    age: 20,
  },
  {
    firstName: "איתן",
    lastName: "אברהמי",
    age: 19,
  },
  {
    firstName: "ישראל-ויאצ'סלב",
    lastName: "אברמוב",
    age: 24,
  },
  {
    firstName: "מנחם (אולג)",
    lastName: "אברמוב",
    age: 18,
  },
  {
    firstName: "אריה-שמעון",
    lastName: "אברמזון",
    age: 22,
    year: 1997,
  },
  {
    firstName: "שמואל (שמוליק)",
    lastName: "אדיב",
    age: 29,
  },
  {
    firstName: "איתי-אבי",
    lastName: "אדלר",
    age: 20,
    year: 1997,
  },
  {
    firstName: "משה",
    lastName: "אדלשטיין",
    age: 31,
  },
  {
    firstName: "יואל",
    lastName: "אדרת",
    age: 36,
  },
  {
    firstName: "שלמה",
    lastName: "אהרון",
    age: 48,
  },
  {
    firstName: "סרג'יו",
    lastName: "אהרונוביץ",
    age: 21,
  },
  {
    firstName: "יששכר (איסי)",
    lastName: "אהרוני",
    age: 31,
  },
  {
    firstName: "אהרון-אורי",
    lastName: "אוחיון",
    age: 24,
  },
  {
    firstName: "משה",
    lastName: "אוחיון",
    age: 20,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "אוחנה",
    age: 24,
  },
  {
    firstName: "יעקב",
    lastName: "אוחנה",
    age: 20,
  },
  {
    firstName: "גבריאל (גבי)",
    lastName: "אוחנונה",
    age: 25,
  },
  {
    firstName: "משה (מוישיק)",
    lastName: "אומן אוקסמן",
    age: 49,
  },
  {
    firstName: "יצחק (איציק)",
    lastName: "אורבכר",
    age: 37,
  },
  {
    firstName: "אבשלום",
    lastName: "אורן",
    age: 24,
  },
  {
    firstName: "אורי",
    lastName: "אזולאי",
    age: 25,
    year: 1996,
  },
  {
    firstName: "אמיל",
    lastName: "אזולאי",
    age: 20,
  },
  {
    firstName: "מקס",
    lastName: "אזולאי",
    age: 29,
  },
  {
    firstName: "ערן",
    lastName: "אזולאי",
    age: 19,
  },
  {
    firstName: "שלום",
    lastName: "אטדג'י",
    age: 20,
  },
  {
    firstName: "ראובן-שמעון",
    lastName: "איבגי",
    age: 20,
  },
  {
    firstName: "צחי",
    lastName: "איטח",
    age: 19,
    year: 2000,
  },
  {
    firstName: "גיל",
    lastName: "אייזן",
    age: 21,
    year: 1997,
  },
  {
    firstName: "רונן",
    lastName: "אילון",
    age: 20,
  },
  {
    firstName: "חזקיה-דריוש (חזי)",
    lastName: "אימני",
    age: 19,
  },
  {
    firstName: "האני",
    lastName: "אל הייב",
    age: 29,
  },
  {
    firstName: "עמר",
    lastName: "אל־קבץ",
    age: 22,
    year: 1999,
  },
  {
    firstName: "רמאון",
    lastName: "אלאב",
    age: 19,
  },
  {
    firstName: "יעקב (קובי)",
    lastName: "אלגמיס",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אודי-יהודה",
    lastName: "אלגרבלי",
    age: 22,
  },
  {
    firstName: "שלמה-מרדכי",
    lastName: "אלגרבלי",
    age: 19,
  },
  {
    firstName: "נחום",
    lastName: "אלה",
    age: 19,
    year: 1998,
  },
  {
    firstName: "אסף-שלמה",
    lastName: "אלון",
    age: 21,
  },
  {
    firstName: "גיא",
    lastName: "אליאש",
    age: 21,
  },
  {
    firstName: "ישי",
    lastName: "אליאש",
    age: 22,
  },
  {
    firstName: "איתמר",
    lastName: "אליה",
    age: 21,
    year: 1997,
  },
  {
    firstName: "עופר",
    lastName: "אליהו",
    age: 20,
  },
  {
    firstName: "אמנון",
    lastName: "אליעז",
    age: 46,
  },
  {
    firstName: "ערן",
    lastName: "אלכאוי",
    age: 24,
  },
  {
    firstName: "אמתי",
    lastName: "אלמדון",
    age: 20,
    year: 1996,
  },
  {
    firstName: "ציון",
    lastName: "אלמלם",
    age: 22,
  },
  {
    firstName: "שלמה (שלומי)",
    lastName: "אלפסי",
    age: 19,
  },
  {
    firstName: "עידן",
    lastName: "אלפר",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אליהו",
    lastName: "אלקיים",
    age: 19,
  },
  {
    firstName: "אברהם (ממושי)",
    lastName: "אלרן לזרוביץ",
    age: 38,
  },
  {
    firstName: "רחמים (רמי)",
    lastName: "לוי אלשייך",
    age: 21,
  },
  {
    firstName: "אבנר",
    lastName: "אלתר",
    age: 20,
    year: 1997,
  },
  {
    firstName: "ניב",
    lastName: "אמויאל",
    age: 19,
  },
  {
    firstName: "משה",
    lastName: "אמסלם",
    age: 19,
  },
  {
    firstName: "מרדכי (מוטי)",
    lastName: "אמרוסי",
    age: 22,
  },
  {
    firstName: "אברהם (אלה)",
    lastName: "אסולין",
    age: 21,
  },
  {
    firstName: "עמית",
    lastName: "אסולין",
    age: 21,
    year: 1998,
  },
  {
    firstName: "סמיר",
    lastName: "אסעד",
    age: 30,
  },
  {
    firstName: "אברהם-גד (אבי)",
    lastName: "אפנר",
    age: 21,
    year: 1997,
  },
  {
    firstName: "עזרא (עוזי)",
    lastName: "אפרים",
    age: 23,
  },
  {
    firstName: "שגיא",
    lastName: "ארזי",
    age: 23,
    year: 1997,
  },
  {
    firstName: "אביב-אברהם (אבי)",
    lastName: "אריאל",
    age: 22,
  },
  {
    firstName: "ערן (ערנו)",
    lastName: "אריאל",
    age: 20,
    year: 1998,
  },
  {
    firstName: "עופר",
    lastName: "אריאלי",
    age: 21,
  },
  {
    firstName: "רן-ראובן",
    lastName: "ארמן",
    age: 21,
    year: 1997,
  },
  {
    firstName: "עומר",
    lastName: "אשד",
    age: 20,
    year: 1998,
  },
  {
    firstName: "נועם",
    lastName: "אשכול",
    age: 21,
  },
  {
    firstName: "רונן",
    lastName: "אשל",
    age: 21,
    year: 1998,
  },
  {
    firstName: "עזרא",
    lastName: "אשר",
    age: 22,
  },
  {
    firstName: "רוני",
    lastName: "אשר",
    age: 30,
  },
  {
    firstName: "אלון-אברהם חי",
    lastName: "בביאן",
    age: 21,
    year: 1997,
  },
  {
    firstName: "דוד",
    lastName: "בגדדי",
    age: 50,
  },
  {
    firstName: "אברהם",
    lastName: "בדו",
    age: 36,
  },
  {
    firstName: "יעקב",
    lastName: "בדרי",
    age: 29,
  },
  {
    firstName: "הרצל",
    lastName: "בובליל",
    age: 18,
  },
  {
    firstName: "יונתן",
    lastName: "בוידן",
    age: 19,
  },
  {
    firstName: "אריה",
    lastName: "בוירסקי",
    age: 22,
  },
  {
    firstName: "רמי",
    lastName: "בוכריס",
    age: 20,
  },
  {
    firstName: "יואל",
    lastName: "בונקר",
    age: 19,
  },
  {
    firstName: "צבי",
    lastName: "בוסקילה",
    age: 20,
  },
  {
    firstName: "זהר",
    lastName: "בועז",
    age: 21,
  },
  {
    firstName: "אברהם-יעקב (אבי)",
    lastName: "בוק",
    age: 22,
    year: 1997,
  },
  {
    firstName: "מישל",
    lastName: "בוקובזה",
    age: 19,
  },
  {
    firstName: "חיים",
    lastName: "בוקטוס",
    age: 21,
  },
  {
    firstName: "מרדכי (מוטי)",
    lastName: "בחרי",
    age: 38,
  },
  {
    firstName: "פול",
    lastName: "ביבס",
    age: 26,
    year: 1997,
  },
  {
    firstName: "אורן-אורי",
    lastName: "ביטון",
    age: 21,
    year: 1997,
  },
  {
    firstName: "דוד",
    lastName: "ביטון",
    age: 38,
  },
  {
    firstName: "יואב",
    lastName: "ביטון",
    age: 25,
  },
  {
    firstName: "מאיר (מיקי)",
    lastName: "ביטון",
    age: 29,
  },
  {
    firstName: "מימון-אמנון",
    lastName: "ביטון",
    age: 19,
  },
  {
    firstName: "מרדכי (מוטי)",
    lastName: "ביטון",
    age: 29,
  },
  {
    firstName: "משה (מושיקו)",
    lastName: "ביטון",
    age: 21,
    year: 1998,
  },
  {
    firstName: "ניסים",
    lastName: "ביטון",
    age: 35,
  },
  {
    firstName: "שגיא",
    lastName: "בלאו",
    age: 19,
  },
  {
    firstName: "ניצן",
    lastName: "בלדרן",
    age: 20,
    year: 1998,
  },
  {
    firstName: "איתן",
    lastName: "בלחסן",
    age: 30,
    year: 1999,
  },
  {
    firstName: "רונן-יהודה",
    lastName: "בלטי",
    age: 21,
  },
  {
    firstName: "רפי (רפאל)",
    lastName: "בללטי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "שרון",
    lastName: "בן אריה",
    age: 22,
  },
  {
    firstName: "אברהם-גל",
    lastName: "בוזגלו",
    age: 28,
  },
  {
    firstName: "גיא-יוסף",
    lastName: "דב",
    age: 21,
  },
  {
    firstName: "אלעד-אפרים",
    lastName: "בן דוד",
    age: 23,
  },
  {
    firstName: "עמרי",
    lastName: "בן זכרי",
    age: 19,
  },
  {
    firstName: "אילן",
    lastName: "בן חיים",
    age: 21,
    year: 1988,
  },
  {
    firstName: "שמעון",
    lastName: "בן יצחק",
    age: 24,
  },
  {
    firstName: "דוד (דודו)",
    lastName: "עמי",
    age: 18,
  },
  {
    firstName: "שלום",
    lastName: "עמי",
    age: 23,
  },
  {
    firstName: "משה",
    lastName: "צור",
    age: 20,
  },
  {
    firstName: "יעקב",
    lastName: "שאנן",
    age: 44,
  },
  {
    firstName: "אלון",
    lastName: "שחר",
    age: 21,
  },
  {
    firstName: "משה",
    lastName: "אבו",
    age: 22,
  },
  {
    firstName: "יוסף",
    lastName: "אור",
    age: 33,
  },
  {
    firstName: "ניר",
    lastName: "בן חיים",
    age: 20,
    year: 1997,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "מוחא",
    age: 19,
    year: 1998,
  },
  {
    firstName: "אשל-אמיר",
    lastName: "בן משה",
    age: 21,
    year: 1996,
  },
  {
    firstName: "אליהו",
    lastName: "עזרא",
    age: 23,
  },
  {
    firstName: "רמי",
    lastName: "צבי",
    age: 26,
  },
  {
    firstName: "קובי",
    lastName: "בן שם",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אברהם",
    lastName: "שמואל",
    age: 36,
  },
  {
    firstName: "רונן־אריה",
    age: 20,
    year: 2000,
  },
  {
    firstName: "יעקב (פקו)",
    lastName: "בנוליאל",
    age: 26,
  },
  {
    firstName: "יצחק-צחי",
    lastName: "בנטוב",
    age: 28,
    year: 1997,
  },
  {
    firstName: "יוסי",
    lastName: "בניון",
    age: 21,
  },
  {
    firstName: "אופיר-אשר",
    lastName: "בסול",
    age: 21,
    year: 1997,
  },
  {
    firstName: "בנימין (בני)",
    lastName: "בסירטמן",
    age: 20,
  },
  {
    firstName: "אברהם (אבי)",
    lastName: "בצלאל",
    age: 20,
  },
  {
    firstName: "ארז-איתן",
    lastName: "בצלאל",
    age: 19,
  },
  {
    firstName: "ניר",
    lastName: "בר",
    age: 20,
  },
  {
    firstName: "אבי",
    lastName: "בר-נס",
    age: 26,
  },
  {
    firstName: "חיים",
    lastName: "בר-נתן",
    age: 19,
  },
  {
    firstName: "שלמה",
    lastName: "בר-ציון",
    age: 48,
  },
  {
    firstName: "יצחק (איציק)",
    lastName: "בר אלי",
    age: 27,
  },
  {
    firstName: "דרור",
    lastName: "בראשי",
    age: 22,
  },
  {
    firstName: "עירן",
    lastName: "ברג",
    age: 19,
  },
  {
    firstName: "יוחנן (יוני)",
    lastName: "ברגר",
    age: 18,
  },
  {
    firstName: "דוד",
    lastName: "ברדה",
    age: 20,
  },
  {
    firstName: "יעקב (קובי)",
    lastName: "ברדס יעקב",
    age: 19,
  },
  {
    firstName: "חן-חנוך",
    lastName: "ברוד",
    age: 22,
  },
  {
    firstName: "עזרא",
    lastName: "ברוך",
    age: 21,
  },
  {
    firstName: "ברוך",
    lastName: "ברונשטיין",
    age: 37,
  },
  {
    firstName: "משה",
    lastName: "ברי",
    age: 23,
  },
  {
    firstName: "סלמאן",
    lastName: "ברכאת",
    age: 32,
  },
  {
    firstName: "יצחק (איציק)",
    lastName: "ברכה",
    age: 39,
  },
  {
    firstName: "בן-ציון-הכהן (בני)",
    lastName: "ברנדלר",
    age: 19,
  },
  {
    firstName: "זאב-דובי",
    lastName: "ברנט",
    age: 20,
  },
  {
    firstName: "עובד-עובדיה",
    lastName: "ברניץ",
    age: 22,
  },
  {
    firstName: "יונתן (יוני)",
    lastName: "ברנס",
    age: 20,
  },
  {
    firstName: "נועם-מיכאל",
    lastName: "ברנע",
    age: 21,
    year: 1999,
  },
  {
    firstName: "מרקו-מאיר",
    lastName: "ברנשטיין",
    age: 21,
  },
  {
    firstName: "יבגני",
    lastName: "ברצלבסקי",
    age: 19,
  },
  {
    firstName: "דותן",
    lastName: "ברק",
    age: 20,
  },
  {
    firstName: "יהודה-יאיר",
    lastName: "ברק",
    age: 20,
  },
  {
    firstName: "שגיא (סגוש)",
    lastName: "ברקוביץ",
    age: 22,
    year: 1997,
  },
  {
    firstName: "שלמה ברקת",
    age: 48,
  },
  {
    firstName: "אבשלום (אבי)",
    lastName: "בשארי",
    age: 20,
  },
  {
    firstName: "חוסיין",
    lastName: "בשיר",
    age: 35,
    year: 1997,
  },
  {
    firstName: "מחמוד",
    lastName: "ג'ומעה",
    age: 22,
  },
  {
    firstName: "סעדאללה",
    lastName: "גאנם",
    age: 35,
  },
  {
    firstName: "גבריאל (גבי)",
    lastName: "גאקמן",
    age: 19,
  },
  {
    firstName: "דוד",
    lastName: "גבאי",
    age: 19,
  },
  {
    firstName: "יעקב (קובי)",
    lastName: "גבאי",
    age: 20,
  },
  {
    firstName: "אסף",
    lastName: "גביש",
    age: 22,
  },
  {
    firstName: "זאב גבע",
    lastName: "גרינברג",
    age: 29,
  },
  {
    firstName: "אברהם גבע",
    lastName: "קליך",
    age: 32,
  },
  {
    firstName: "עידן",
    lastName: "גבריאל",
    age: 20,
    year: 1996,
  },
  {
    firstName: "ציון",
    lastName: "גבריאל",
    age: 21,
  },
  {
    firstName: "רישרד (ריצ'רד)",
    lastName: "גברילוביץ",
    age: 23,
  },
  {
    firstName: "מולטו-אשר",
    lastName: "גדעון",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אבישי (שייקוש)",
    lastName: "גדרון",
    age: 19,
    year: 1997,
  },
  {
    firstName: "אייל",
    lastName: "גואטה",
    age: 21,
    year: 1999,
  },
  {
    firstName: "אברהם",
    lastName: "גודינצקי",
    age: 20,
  },
  {
    firstName: "מיכה (מיכי)",
    lastName: "גוטליב",
    age: 20,
    year: 1997,
  },
  {
    firstName: "יוסי (יוסקה)",
    lastName: "גוילי",
    age: 23,
  },
  {
    firstName: "תומר",
    lastName: "גולדברג",
    age: 20,
    year: 1997,
  },
  {
    firstName: "שבתאי",
    lastName: "גולמבה",
    age: 22,
  },
  {
    firstName: "ריקרדו-דניאל",
    lastName: "גולמן",
    age: 28,
  },
  {
    firstName: "אביב-ששון",
    lastName: "גולן",
    age: 24,
    year: 1997,
  },
  {
    firstName: "אסף-חנן",
    lastName: "גולן",
    age: 19,
  },
  {
    firstName: "גיא",
    lastName: "גולן",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אביב",
    lastName: "גונן",
    age: 21,
    year: 1997,
  },
  {
    firstName: "עמרי-ספי (המיש)",
    lastName: "גונן",
    age: 21,
  },
  {
    firstName: "יצחק (איז'ו)",
    lastName: "גוס",
    age: 30,
  },
  {
    firstName: "בני גור",
    lastName: "גבירץ",
    age: 36,
  },
  {
    firstName: "גנאדי",
    lastName: "גורבנוב",
    age: 19,
  },
  {
    firstName: "ישראל גורן",
    lastName: "ויצקוביץ",
    age: 28,
  },
  {
    firstName: "תמיר",
    lastName: "גלזר",
    age: 24,
    year: 1997,
  },
  {
    firstName: "עמיר",
    lastName: "גלילי",
    age: 40,
  },
  {
    firstName: "יבגני",
    lastName: "גלרמן",
    age: 21,
  },
  {
    firstName: "ניר-ישראל",
    lastName: "גנדלברג",
    age: 20,
    year: 1996,
  },
  {
    firstName: "אלברט-אברהם",
    lastName: "גנון",
    age: 30,
  },
  {
    firstName: "ולרי",
    lastName: "גנזמן",
    age: 22,
    year: 1996,
  },
  {
    firstName: "ידידיה",
    lastName: "גפן",
    age: 20,
    year: 2000,
  },
  {
    firstName: "גבריאל (גבי)",
    lastName: "גפני",
    age: 30,
  },
  {
    firstName: "אמיר",
    lastName: "גפר",
    age: 18,
  },
  {
    firstName: "אהוד (אודי)",
    lastName: "גראוברט",
    age: 22,
  },
  {
    firstName: "צבי",
    lastName: "גרוסמן",
    age: 22,
    year: 1997,
  },
  {
    firstName: "משה",
    lastName: "גרידי",
    age: 31,
  },
  {
    firstName: "דוד",
    lastName: "גרינולד",
    age: 20,
  },
  {
    firstName: "יעקב",
    lastName: "גרנדה",
    age: 39,
  },
  {
    firstName: "דוד-יעקב",
    lastName: "גרנית",
    age: 22,
  },
  {
    firstName: "ארז",
    lastName: "גרשטיין",
    age: 39,
    year: 1999,
  },
  {
    firstName: "צחי",
    lastName: "דאלי",
    age: 20,
  },
  {
    firstName: "יהונתן (יוני)",
    lastName: "דבירי",
    age: 20,
    year: 1998,
  },
  {
    firstName: "מאהר",
    lastName: "דגש",
    age: 27,
    year: 1997,
  },
  {
    firstName: "אורי",
    lastName: "דהאן",
    age: 29,
  },
  {
    firstName: "אסף",
    lastName: "דהאן",
    age: 20,
    year: 1997,
  },
  {
    firstName: "יורם-יעקב",
    lastName: "דהאן",
    age: 32,
    year: 1996,
  },
  {
    firstName: "מאיר",
    lastName: "דהן",
    age: 25,
  },
  {
    firstName: "מוריס",
    lastName: "דהן",
    age: 31,
  },
  {
    firstName: "משה",
    lastName: "דהן",
    age: 19,
  },
  {
    firstName: "עמרם",
    lastName: "דהן",
    age: 18,
  },
  {
    firstName: "ניר",
    lastName: "דובב",
    age: 19,
  },
  {
    firstName: "אורי",
    lastName: "דוד",
    age: 19,
  },
  {
    firstName: "ארז-טל",
    lastName: "דוד",
    age: 20,
  },
  {
    firstName: "שמעון (שימי)",
    lastName: "דוד",
    age: 21,
  },
  {
    firstName: "נפתלי (תלי)",
    lastName: "דודלס",
    age: 24,
  },
  {
    firstName: "רועי (דומבי)",
    lastName: "דומב",
    age: 20,
  },
  {
    firstName: "זהר",
    lastName: "דורון",
    age: 21,
    year: 1998,
  },
  {
    firstName: "סלאמה",
    lastName: "דיאב",
    age: 26,
  },
  {
    firstName: "סמיר",
    lastName: "דיב",
    age: 22,
  },
  {
    firstName: "עופר",
    lastName: "דיין",
    age: 21,
  },
  {
    firstName: "וילי",
    lastName: "דיקמן",
    age: 59,
  },
  {
    firstName: "הנרי (ריקו)",
    lastName: "דנה",
    age: 45,
  },
  {
    firstName: "שמעיה-אביחי",
    lastName: "דנוך",
    age: 19,
  },
  {
    firstName: "סטפן-איציק",
    lastName: "דניאל",
    age: 29,
  },
  {
    firstName: "נתנאל",
    lastName: "דניאלוב",
    age: 21,
  },
  {
    firstName: "דן",
    lastName: "דרום",
    age: 28,
  },
  {
    firstName: "אלכסנדר",
    lastName: "דרוקר",
    age: 38,
  },
  {
    firstName: "מרדכי",
    lastName: "דרעי",
    age: 20,
  },
  {
    firstName: "מרדכי",
    lastName: "דרעי",
    age: 19,
  },
  {
    firstName: "חסן",
    lastName: "הדאיה",
    age: 28,
  },
  {
    firstName: "אריק-סלומון",
    lastName: "הוימן",
    age: 24,
  },
  {
    firstName: "מרקוס",
    lastName: "הוכשטיין",
    age: 21,
  },
  {
    firstName: "אביקם-אבי (ראובן)",
    lastName: "הופמן",
    age: 19,
  },
  {
    firstName: "אלחנדרו-אלה",
    lastName: "הופמן",
    age: 19,
    year: 1997,
  },
  {
    firstName: "עלי",
    lastName: "הורנר",
    age: 48,
  },
  {
    firstName: "נאייף",
    lastName: "הייב",
    age: 35,
  },
  {
    firstName: "יוחנן-אברהם",
    lastName: "הילברג",
    age: 23,
    year: 1997,
  },
  {
    firstName: "דורון",
    lastName: "הירשקוביץ",
    age: 20,
    year: 1999,
  },
  {
    firstName: "יעקב הכהן",
    lastName: "טראב-מסלתון",
    age: 21,
  },
  {
    firstName: "יצחק-מאיר (איציק)",
    lastName: "הלוי קליין",
    age: 25,
  },
  {
    firstName: "אורי",
    lastName: "הלמן",
    age: 21,
  },
  {
    firstName: "משה",
    lastName: "הרוש",
    age: 23,
    year: 1996,
  },
  {
    firstName: "יואב",
    lastName: "הרשושנים",
    age: 21,
  },
  {
    firstName: "עשהאל (אסי)",
    lastName: "והב",
    age: 20,
  },
  {
    firstName: "שי",
    lastName: "וולשטיין",
    age: 22,
  },
  {
    firstName: "חנן (חוני)",
    lastName: "וורבר",
    age: 23,
  },
  {
    firstName: "רמזי",
    lastName: "וחש",
    age: 27,
  },
  {
    firstName: "ארי-יחיאל",
    lastName: "וידל",
    age: 20,
  },
  {
    firstName: "מאיר-שלמה",
    lastName: "וידמן",
    age: 35,
  },
  {
    firstName: "שמואל-ינאי",
    lastName: "ויינשטוק",
    age: 20,
  },
  {
    firstName: "ברוך",
    lastName: "וייצמן",
    age: 39,
  },
  {
    firstName: "יעקב (ג'קי)",
    lastName: "וייר",
    age: 21,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "וינשטוק",
    age: 19,
  },
  {
    firstName: "יובל",
    lastName: "וינשטיין",
    age: 24,
  },
  {
    firstName: "ישי-רונן",
    lastName: "ויסמן",
    age: 22,
  },
  {
    firstName: "ארנון",
    lastName: "וספי",
    age: 19,
  },
  {
    firstName: "אייל דרור",
    lastName: "וקנין",
    age: 21,
  },
  {
    firstName: "רון",
    lastName: "ורדי",
    age: 20,
  },
  {
    firstName: "רון",
    lastName: "ורנר",
    age: 22,
  },
  {
    firstName: "רונן",
    lastName: "ז'ורנו",
    age: 21,
  },
  {
    firstName: "יהושע-יוסף",
    lastName: "זאדה",
    age: 28,
  },
  {
    firstName: "איתן",
    lastName: "זהבי",
    age: 28,
  },
  {
    firstName: "דן (דני)",
    lastName: "זהבי",
    age: 19,
    year: 1997,
  },
  {
    firstName: "שאול (שאולי)",
    lastName: "זהבי",
    age: 27,
  },
  {
    firstName: "שמעון",
    lastName: "זהבי",
    age: 39,
  },
  {
    firstName: "זאביק",
    lastName: "זומרפלד",
    age: 21,
    year: 1997,
  },
  {
    firstName: "דוד",
    lastName: "זונטג",
    age: 47,
  },
  {
    firstName: "זיאד",
    lastName: "זיאדה",
    age: 21,
  },
  {
    firstName: "סאלח-כאמל",
    lastName: "זידאן",
    age: 24,
  },
  {
    firstName: "אמיר",
    lastName: "זידנר",
    age: 19,
  },
  {
    firstName: "חנן (חנינה) זיו",
    lastName: "זזניקביץ",
    age: 30,
  },
  {
    firstName: "עוזי",
    lastName: "זילבר",
    age: 42,
  },
  {
    firstName: "אלכסנדר-לרנד (אלכס)",
    lastName: "זינגר",
    age: 25,
  },
  {
    firstName: "יאיר",
    lastName: "זינר",
    age: 30,
  },
  {
    firstName: "אוהד",
    lastName: "זך",
    age: 19,
    year: 1998,
  },
  {
    firstName: "ניסים-ניר",
    lastName: "זלאיט",
    age: 20,
  },
  {
    firstName: "רפאל (רפי)",
    lastName: "זנגוויל",
    age: 24,
    year: 2000,
  },
  {
    firstName: "אורן",
    lastName: "זריף",
    age: 21,
    year: 1997,
  },
  {
    firstName: "רוקון ח'טיב",
    lastName: "זויהד",
    age: 20,
  },
  {
    firstName: "חמד",
    lastName: "חאטיב",
    age: 26,
  },
  {
    firstName: "כיואן",
    lastName: "חאמד",
    age: 30,
  },
  {
    firstName: "חליל",
    lastName: "חדאד",
    age: 28,
  },
  {
    firstName: "גיא-שלם",
    lastName: "חדד",
    age: 21,
  },
  {
    firstName: "יוסף (שושן)",
    lastName: "חדד",
    age: 31,
  },
  {
    firstName: "יצחק-יהודה (צ'יקו)",
    lastName: "חדד",
    age: 19,
  },
  {
    firstName: "מוחמד",
    lastName: "חוג'יראת",
    age: 27,
    year: 1996,
  },
  {
    firstName: "ערן",
    lastName: "חודדה",
    age: 20,
  },
  {
    firstName: "יחזקאל",
    lastName: "חורש",
    age: 39,
    year: 1997,
  },
  {
    firstName: "ישראל",
    lastName: "חושני",
    age: 35,
  },
  {
    firstName: "ניב",
    lastName: "חזון",
    age: 19,
  },
  {
    firstName: "אבנר-כפיר",
    lastName: "חזי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "אילן",
    lastName: "חזיזה",
    age: 20,
  },
  {
    firstName: "אפרים (אפי)",
    lastName: "חזן",
    age: 24,
  },
  {
    firstName: "גולן (גולי)",
    lastName: "חזן",
    age: 20,
  },
  {
    firstName: "שמעון",
    lastName: "חזן",
    age: 24,
  },
  {
    firstName: "נג'ם",
    lastName: "חזראן",
    age: 20,
  },
  {
    firstName: "מהדי",
    lastName: "חטיב",
    age: 21,
    year: 1997,
  },
  {
    firstName: "יוסף",
    lastName: "חי-ציון",
    age: 38,
  },
  {
    firstName: "אברהם",
    lastName: "חידו",
    age: 41,
  },
  {
    firstName: "רונן (רונני)",
    lastName: "חיון",
    age: 19,
    year: 1997,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "חיים",
    age: 23,
  },
  {
    firstName: "שאול (שאולי)",
    lastName: "חילביץ",
    age: 20,
  },
  {
    firstName: "שבתאי",
    lastName: "חכמון",
    age: 37,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "חליבה",
    age: 18,
  },
  {
    firstName: "אהוד-שמשון",
    lastName: "חלמיש",
    age: 20,
  },
  {
    firstName: "זהר",
    lastName: "חלמיש",
    age: 21,
  },
  {
    firstName: "רונן",
    lastName: "חלפון",
    age: 35,
    year: 1997,
  },
  {
    firstName: "חיים",
    lastName: "חנוך",
    age: 19,
  },
  {
    firstName: "דרור (דורי)",
    lastName: "חנן",
    age: 20,
  },
  {
    firstName: "עמית (מיצכה)",
    lastName: "חסדאי",
    age: 21,
  },
  {
    firstName: "אשר",
    lastName: "חסין",
    age: 23,
  },
  {
    firstName: "עופר",
    lastName: "חרוש",
    age: 20,
  },
  {
    firstName: "סאלח",
    lastName: "טאפש",
    age: 21,
  },
  {
    firstName: "רז",
    lastName: "טבי",
    age: 22,
    year: 1997,
  },
  {
    firstName: "אריה",
    lastName: "טובול",
    age: 20,
  },
  {
    firstName: "לירז (רז)",
    lastName: "טיטו",
    age: 21,
    year: 1999,
  },
  {
    firstName: "גיא",
    lastName: "טל",
    age: 20,
  },
  {
    firstName: "אילן טל",
    lastName: "טאוסיג",
    age: 33,
  },
  {
    firstName: "איתן טל",
    lastName: "טמקין",
    age: 42,
  },
  {
    firstName: "תדהר",
    lastName: "טמפלהוף",
    age: 24,
    year: 2000,
  },
  {
    firstName: "רון",
    lastName: "טנדיט",
    age: 20,
  },
  {
    firstName: "אסף-יחזקאל",
    lastName: "טננבאום",
    age: 21,
  },
  {
    firstName: "אביב",
    lastName: "טרוטנר",
    age: 20,
  },
  {
    firstName: "שמעון יהב",
    lastName: "והב",
    age: 31,
  },
  {
    firstName: "נפתלי יהב",
    lastName: "שוסטק",
    age: 36,
  },
  {
    firstName: "אמיר",
    lastName: "יואלי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "ירון",
    lastName: "יוגב",
    age: 22,
  },
  {
    firstName: "רוסלן",
    lastName: "יוסיפוב",
    age: 21,
    year: 1997,
  },
  {
    firstName: "יחזקאל",
    lastName: "יחיא",
    age: 37,
  },
  {
    firstName: "אהרן",
    lastName: "ינובסקי",
    age: 37,
  },
  {
    firstName: "רונן (צ'פל)",
    lastName: "יפה",
    age: 19,
  },
  {
    firstName: "ארז",
    lastName: "יצחק",
    age: 19,
    year: 1996,
  },
  {
    firstName: "צור-צבי",
    lastName: "ישראל",
    age: 22,
  },
  {
    firstName: "נדב",
    lastName: "ישראלי",
    age: 20,
  },
  {
    firstName: "מיכאל (מיקי)",
    lastName: "כץ",
    age: 20,
    year: 1997,
  },
  {
    firstName: "ליאור-בנימין",
    lastName: "כביר",
    age: 20,
  },
  {
    firstName: "הראל",
    lastName: "כברה",
    age: 21,
  },
  {
    firstName: "אור",
    lastName: "כהן",
    age: 20,
    year: 1998,
  },
  {
    firstName: "אייל-מיקי",
    lastName: "כהן",
    age: 20,
    year: 1998,
  },
  {
    firstName: "אייל (בבי)",
    lastName: "כהן",
    age: 19,
  },
  {
    firstName: "אילן",
    lastName: "כהן",
    age: 21,
  },
  {
    firstName: "דוד (דידי)",
    lastName: "כהן",
    age: 21,
  },
  {
    firstName: "דותן-יצחק",
    lastName: "כהן",
    age: 22,
    year: 1997,
  },
  {
    firstName: "טל",
    lastName: "כהן",
    age: 20,
  },
  {
    firstName: "יהודה",
    lastName: "כהן",
    age: 40,
  },
  {
    firstName: "יהודה (אודי)",
    lastName: "כהן",
    age: 18,
  },
  {
    firstName: "יוסף (ג'רארד)",
    lastName: "כהן",
    age: 40,
  },
  {
    firstName: "יעקב",
    lastName: "כהן",
    age: 23,
  },
  {
    firstName: "ירמי",
    lastName: "כהן",
    age: 23,
    year: 1997,
  },
  {
    firstName: "מאיר (דובי)",
    lastName: "כהן",
    age: 20,
  },
  {
    firstName: "רוברט (רובי)",
    lastName: "כהן",
    age: 21,
  },
  {
    firstName: "רונן",
    lastName: "כהן",
    age: 20,
    year: 1997,
  },
  {
    firstName: "רמי",
    lastName: "כהן",
    age: 24,
  },
  {
    firstName: "שחר",
    lastName: "כהן",
    age: 20,
  },
  {
    firstName: "שלמה",
    lastName: "כהן",
    age: 32,
  },
  {
    firstName: "ששון",
    lastName: "כהן",
    age: 25,
  },
  {
    firstName: "תום",
    lastName: "כיתאין",
    age: 21,
    year: 1997,
  },
  {
    firstName: "גדעון (גידי)",
    lastName: "כליף",
    age: 27,
  },
  {
    firstName: "מרדכי",
    lastName: "כליפה",
    age: 29,
  },
  {
    firstName: "עמוס",
    lastName: "כלפה",
    age: 29,
    year: 1998,
  },
  {
    firstName: "אורן",
    lastName: "כמיל",
    age: 19,
  },
  {
    firstName: "חיים",
    lastName: "כנפו",
    age: 19,
  },
  {
    firstName: "חן",
    lastName: "כנרתי",
    age: 22,
  },
  {
    firstName: "סאלח",
    lastName: "כעבייה",
    age: 22,
  },
  {
    firstName: "רפי (פירוז)",
    lastName: "כשר",
    age: 20,
  },
  {
    firstName: "אבי",
    lastName: "לב",
    age: 18,
  },
  {
    firstName: "גל",
    lastName: "לב-רן",
    age: 22,
    year: 1997,
  },
  {
    firstName: "דב (דובי)",
    lastName: "לבבי",
    age: 27,
  },
  {
    firstName: "ישעיהו (אישי)",
    lastName: "לביא",
    age: 31,
  },
  {
    firstName: "יריב",
    lastName: "להב",
    age: 22,
  },
  {
    firstName: "אבישי",
    lastName: "לוי",
    age: 27,
    year: 1997,
  },
  {
    firstName: "אייל",
    lastName: "לוי",
    age: 20,
  },
  {
    firstName: "דב",
    lastName: "לוי",
    age: 20,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "לוי",
    age: 21,
    year: 1996,
  },
  {
    firstName: "יצחק (איציק)",
    lastName: "לוי",
    age: 19,
  },
  {
    firstName: "ישי-דב",
    lastName: "לוי",
    age: 20,
  },
  {
    firstName: "מישאל-אייל",
    lastName: "לוי",
    age: 22,
  },
  {
    firstName: "מרדכי (מוטי)",
    lastName: "לוי",
    age: 20,
  },
  {
    firstName: "שילה",
    lastName: "לוי",
    age: 21,
    year: 1997,
  },
  {
    firstName: "רם",
    lastName: "לוינס",
    age: 22,
    year: 1997,
  },
  {
    firstName: "גל",
    lastName: "לוינסון",
    age: 21,
  },
  {
    firstName: "דוד (דודי)",
    lastName: "לזימי",
    age: 20,
  },
  {
    firstName: "מרדכי (מולו)",
    lastName: "ליבליך",
    age: 37,
  },
  {
    firstName: "אברהם (אבי)",
    lastName: "לימואי",
    age: 21,
    year: 1998,
  },
  {
    firstName: "גד (גדי)",
    lastName: "ליפסקי",
    age: 19,
  },
  {
    firstName: "פנחס (פיני)",
    lastName: "ליפשיץ",
    age: 34,
  },
  {
    firstName: "יורם לירן",
    lastName: "(ליקרמן)",
    age: 35,
  },
  {
    firstName: "נדב",
    lastName: "לישצינסקי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "לירון",
    lastName: "לנג",
    age: 20,
  },
  {
    firstName: "דביר",
    lastName: "לניר",
    age: 22,
    year: 1997,
  },
  {
    firstName: "אילן",
    lastName: "לנציצקי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "אמיר",
    lastName: "מאיר",
    age: 19,
    year: 2000,
  },
  {
    firstName: "לזר",
    lastName: "מאיר",
    age: 46,
  },
  {
    firstName: "חיים",
    lastName: "מדר",
    age: 36,
  },
  {
    firstName: "יוסף",
    lastName: "מויאל",
    age: 21,
  },
  {
    firstName: "דוד",
    lastName: "מועלם",
    age: 18,
  },
  {
    firstName: "משה",
    lastName: "מועלם",
    age: 32,
    year: 1997,
  },
  {
    firstName: "חסין",
    lastName: "מוקטרן",
    age: 33,
  },
  {
    firstName: "אביב",
    lastName: "מור",
    age: 20,
  },
  {
    firstName: "אילן",
    lastName: "מור",
    age: 20,
  },
  {
    firstName: "דביר-יעקב",
    lastName: "מור-חיים",
    age: 20,
  },
  {
    firstName: "יורם",
    lastName: "מור יוסף",
    age: 19,
  },
  {
    firstName: "גמיל",
    lastName: "מורד",
    age: 32,
  },
  {
    firstName: "דניאל-ישראל",
    lastName: "מושיץ",
    age: 21,
  },
  {
    firstName: "גלעד",
    lastName: "מושל",
    age: 20,
    year: 1997,
  },
  {
    firstName: "רן",
    lastName: "מזומן",
    age: 22,
    year: 1997,
  },
  {
    firstName: "בועז",
    lastName: "מזר",
    age: 20,
  },
  {
    firstName: "אברהם",
    lastName: "מזרחי",
    age: 20,
  },
  {
    firstName: "יצחק (צחי)",
    lastName: "מזרחי",
    age: 21,
    year: 1996,
  },
  {
    firstName: "עדי",
    lastName: "מזרחי",
    age: 33,
  },
  {
    firstName: "ציון",
    lastName: "מזרחי",
    age: 24,
  },
  {
    firstName: "אליהו",
    lastName: "מטלון",
    age: 40,
  },
  {
    firstName: "אמיר",
    lastName: "מי-טל",
    age: 29,
  },
  {
    firstName: "גל",
    lastName: "מיזלס",
    age: 24,
    year: 1997,
  },
  {
    firstName: "גד",
    lastName: "מיינפלד",
    age: 19,
  },
  {
    firstName: "ולדיסלב",
    lastName: "מיכאילוב",
    age: 22,
    year: 1997,
  },
  {
    firstName: "אפרים (אפי)",
    lastName: "מיכאל",
    age: 28,
  },
  {
    firstName: "אברהם (אבי)",
    lastName: "מילר",
    age: 23,
  },
  {
    firstName: "דניאל (דני) מילר",
    age: 21,
  },
  {
    firstName: "שחר",
    lastName: "מינס",
    age: 21,
    year: 1998,
  },
  {
    firstName: "זהר",
    lastName: "מינץ",
    age: 21,
    year: 1996,
  },
  {
    firstName: "עידן",
    lastName: "מינקר",
    age: 21,
    year: 1997,
  },
  {
    firstName: "הלל",
    lastName: "מישייב",
    age: 20,
  },
  {
    firstName: "גלעד-משה",
    lastName: "מישייקר",
    age: 20,
    year: 1997,
  },
  {
    firstName: "נדב-מנחם",
    lastName: "מלוא",
    age: 24,
    year: 1997,
  },
  {
    firstName: "רונן-ויקטור",
    lastName: "מלכה",
    age: 19,
  },
  {
    firstName: "צחי מלכה",
    lastName: "גרינברג",
    age: 21,
    year: 2000,
  },
  {
    firstName: "שבתאי",
    lastName: "מלכי",
    age: 26,
  },
  {
    firstName: "דני",
    lastName: "מלמד",
    age: 21,
  },
  {
    firstName: "יעקב (קובי)",
    lastName: "מלמד",
    age: 20,
    year: 1997,
  },
  {
    firstName: "מנדל (מישה)",
    lastName: "מלמד",
    age: 37,
  },
  {
    firstName: "ודים",
    lastName: "מלניק",
    age: 34,
    year: 1997,
  },
  {
    firstName: "אורן-אברהם",
    lastName: "מלצר",
    age: 21,
  },
  {
    firstName: "אריה",
    lastName: "ממו",
    age: 25,
  },
  {
    firstName: "איתן-יעקב",
    lastName: "ממן",
    age: 26,
    year: 1997,
  },
  {
    firstName: "גיורא",
    lastName: "ממן",
    age: 19,
  },
  {
    firstName: "שמעון",
    lastName: "מנדיל",
    age: 26,
  },
  {
    firstName: "סלאח",
    lastName: "מעדי",
    age: 33,
  },
  {
    firstName: "אורי",
    lastName: "מעוז",
    age: 22,
  },
  {
    firstName: "ישראל",
    lastName: "מעטוף",
    age: 21,
  },
  {
    firstName: "מרדכי הראל",
    lastName: "מעלומיה",
    age: 49,
  },
  {
    firstName: "יהודה",
    lastName: "מצגר",
    age: 21,
  },
  {
    firstName: "צבי-יהודה (צביקה)",
    lastName: "מקליס",
    age: 21,
  },
  {
    firstName: "אלון",
    lastName: "מרון",
    age: 26,
  },
  {
    firstName: "יוסף-יהודה (ספי)",
    lastName: "מרמלשטיין",
    age: 26,
  },
  {
    firstName: "אליהו (אלי)",
    lastName: "מרסיאנו",
    age: 32,
  },
  {
    firstName: "אברהם",
    lastName: "משה",
    age: 19,
  },
  {
    firstName: "דרור",
    lastName: "משה",
    age: 22,
  },
  {
    firstName: "יורם",
    lastName: "משה",
    age: 18,
  },
  {
    firstName: "עמאד",
    lastName: "נבואני",
    age: 21,
  },
  {
    firstName: "משה-מולו",
    lastName: "נגטו",
    age: 23,
    year: 1999,
  },
  {
    firstName: "מעוז",
    lastName: "נגר",
    age: 20,
  },
  {
    firstName: "שלמה",
    lastName: "נגר",
    age: 19,
  },
  {
    firstName: "בנימין (בני)",
    lastName: "נהון",
    age: 21,
  },
  {
    firstName: "אהד-ניר",
    lastName: "נחמיאס",
    age: 20,
    year: 1998,
  },
  {
    firstName: "ליאור",
    lastName: "ניב",
    age: 21,
    year: 2000,
  },
  {
    firstName: "אוהד (דדי)",
    lastName: "ניסים",
    age: 20,
  },
  {
    firstName: "יובל",
    lastName: "ניר",
    age: 22,
    year: 1997,
  },
  {
    firstName: "מוחמד",
    lastName: "נפאע",
    age: 31,
  },
  {
    firstName: "גיא",
    lastName: "נתנאל",
    age: 19,
  },
  {
    firstName: "מרזוק",
    lastName: "סאבק",
    age: 44,
  },
  {
    firstName: "משה (שיקו)",
    lastName: "סבן",
    age: 20,
    year: 1997,
  },
  {
    firstName: "צפריר (צפי)",
    lastName: "סגל",
    age: 20,
  },
  {
    firstName: "ניב",
    lastName: "סדן",
    age: 19,
    year: 1997,
  },
  {
    firstName: "ישראל-משולם סדן",
    lastName: "נפחא",
    age: 21,
  },
  {
    firstName: "גדי",
    lastName: "סואד",
    age: 20,
  },
  {
    firstName: "דיאב",
    lastName: "סואעד",
    age: 36,
  },
  {
    firstName: "גיא",
    lastName: "סודאי",
    age: 19,
  },
  {
    firstName: "יצחק",
    lastName: "סויסה",
    age: 22,
  },
  {
    firstName: "שמעון",
    lastName: "סוסן",
    age: 44,
  },
  {
    firstName: "יורם",
    lastName: "סופי",
    age: 18,
  },
  {
    firstName: "רונן",
    lastName: "סופר",
    age: 21,
  },
  {
    firstName: "צבי (צביקה)",
    lastName: "סטנקוב",
    age: 19,
  },
  {
    firstName: "אסף-יעקב",
    lastName: "סיבוני",
    age: 21,
    year: 1997,
  },
  {
    firstName: "יוסף",
    lastName: "סילוק",
    age: 20,
  },
  {
    firstName: "עמיר",
    lastName: "סיני",
    age: 20,
  },
  {
    firstName: "ריאד",
    lastName: "סיף",
    age: 20,
  },
  {
    firstName: "שמשון",
    lastName: "סלימי",
    age: 37,
  },
  {
    firstName: "יהודה",
    lastName: "סלם",
    age: 20,
    year: 1998,
  },
  {
    firstName: "משה",
    lastName: "סלע",
    age: 36,
  },
  {
    firstName: "עמית-ששון",
    lastName: "סלע",
    age: 21,
  },
  {
    firstName: "אליעזר (אלי)",
    lastName: "סלפטר",
    age: 30,
  },
  {
    firstName: "אורי",
    lastName: "סמואלוב",
    age: 21,
    year: 1998,
  },
  {
    firstName: "נביל",
    lastName: "סמור",
    age: 19,
  },
  {
    firstName: "אבנר",
    lastName: "סנחאני",
    age: 20,
  },
  {
    firstName: "פואד",
    lastName: "סעד",
    age: 33,
  },
  {
    firstName: "מרדכי",
    lastName: "סעידיאן",
    age: 23,
  },
  {
    firstName: "יואב",
    lastName: "סקל",
    age: 20,
  },
  {
    firstName: "וסאם",
    lastName: "סרחאן",
    age: 20,
  },
  {
    firstName: "חוסין-עמיר",
    lastName: "עאמר",
    age: 31,
  },
  {
    firstName: "כרים",
    lastName: "עאמר",
    age: 23,
  },
  {
    firstName: "ריאד",
    lastName: "עאמר",
    age: 28,
  },
  {
    firstName: "זהר-סבח",
    lastName: "עבדה",
    age: 35,
  },
  {
    firstName: "ניר",
    lastName: "עברון",
    age: 21,
  },
  {
    firstName: "ישיש",
    lastName: "עדן",
    age: 44,
    year: 1997,
  },
  {
    firstName: "אברהם אבי",
    lastName: "עובד",
    age: 31,
  },
  {
    firstName: "אריאל",
    lastName: "עובדיה",
    age: 21,
  },
  {
    firstName: "אמיל",
    lastName: "עווידה",
    age: 23,
  },
  {
    firstName: "שקד",
    lastName: "עוזרי",
    age: 25,
    year: 2000,
  },
  {
    firstName: "חמדי",
    lastName: "עוקלה",
    age: 47,
  },
  {
    firstName: "רוני",
    lastName: "עזרא",
    age: 19,
  },
  {
    firstName: "שרון",
    lastName: "עזריאל",
    age: 19,
  },
  {
    firstName: "מוחמד",
    lastName: "עיסאת",
    age: 31,
  },
  {
    firstName: "יהונתן (יוני)",
    lastName: "עמדי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "דניאל (דני)",
    lastName: "עמר",
    age: 20,
  },
  {
    firstName: "יהודה",
    lastName: "עמר",
    age: 25,
  },
  {
    firstName: "יותם",
    lastName: "ענבר",
    age: 20,
  },
  {
    firstName: "נדים",
    lastName: "ענבר",
    age: 19,
  },
  {
    firstName: "רם",
    lastName: "ענבר",
    age: 22,
  },
  {
    firstName: "נועם",
    lastName: "עציוני",
    age: 20,
    year: 1997,
  },
  {
    firstName: "שי (שייקה)",
    lastName: "עקירב",
    age: 20,
  },
  {
    firstName: "גמאל",
    lastName: "פארס",
    age: 30,
  },
  {
    firstName: "נאזם",
    lastName: "פארס",
    age: 26,
  },
  {
    firstName: "סלמאן",
    lastName: "פארס",
    age: 25,
  },
  {
    firstName: "רביח",
    lastName: "פארס",
    age: 30,
  },
  {
    firstName: "מוחמד-אלהייב",
    lastName: "פואז",
    age: 27,
  },
  {
    firstName: "צביקה",
    lastName: "פוגל",
    age: 28,
  },
  {
    firstName: "גדעון",
    lastName: "פוזנר",
    age: 22,
    year: 1997,
  },
  {
    firstName: "שלמה (שלומי)",
    lastName: "פיזואתי",
    age: 19,
    year: 1997,
  },
  {
    firstName: "דן (דנסי)",
    lastName: "פיליפ",
    age: 26,
  },
  {
    firstName: "יוסף (יוסי)",
    lastName: "פינק",
    age: 21,
  },
  {
    firstName: "אברהם-אבא (אבי)",
    lastName: "פישר",
    age: 22,
  },
  {
    firstName: "דוד",
    lastName: "פלד-חדד",
    age: 43,
  },
  {
    firstName: "מנחם (מני)",
    lastName: "פלדמן",
    age: 20,
    year: 1997,
  },
  {
    firstName: "משה",
    lastName: "פנדו",
    age: 38,
  },
  {
    firstName: "לירון",
    lastName: "פניני",
    age: 22,
  },
  {
    firstName: "ויטלי",
    lastName: "פסחוב",
    age: 20,
    year: 1997,
  },
  {
    firstName: "שותא",
    lastName: "פפיסמידוב",
    age: 27,
  },
  {
    firstName: "אלק",
    lastName: "פרגמנט",
    age: 32,
  },
  {
    firstName: "רז",
    lastName: "פרומוביץ",
    age: 19,
    year: 1998,
  },
  {
    firstName: "אורי-שרגא",
    lastName: "פרידמן",
    age: 21,
  },
  {
    firstName: "מגן",
    lastName: "פרידמן",
    age: 22,
    year: 1998,
  },
  {
    firstName: "גבריאל (גבי)",
    lastName: "פרמוטי",
    age: 21,
  },
  {
    firstName: "הרן-אליעזר",
    lastName: "פרנס",
    age: 21,
    year: 1997,
  },
  {
    firstName: "צור",
    lastName: "פרנס",
    age: 21,
    year: 1996,
  },
  {
    firstName: "אוריאל",
    lastName: "פרץ",
    age: 22,
    year: 1998,
  },
  {
    firstName: "ארמונד",
    lastName: "פרץ",
    age: 38,
  },
  {
    firstName: "ערן-חי",
    lastName: "פרץ",
    age: 21,
    year: 1997,
  },
  {
    firstName: "יפתח",
    lastName: "פשחור",
    age: 20,
  },
  {
    firstName: "ארן-ערן",
    lastName: "צבאג",
    age: 20,
  },
  {
    firstName: "ירון",
    lastName: "צופיוף הכהן",
    age: 20,
    year: 1997,
  },
  {
    firstName: "אלון",
    lastName: "צור",
    age: 30,
  },
  {
    firstName: "יונתן",
    lastName: "צירקל",
    age: 22,
    year: 1997,
  },
  {
    firstName: "יאיר",
    lastName: "צפריר",
    age: 21,
  },
  {
    firstName: "נפתלי",
    lastName: "צריקר",
    age: 19,
  },
  {
    firstName: "אמנון",
    lastName: "קדמון",
    age: 19,
  },
  {
    firstName: "הדר",
    lastName: "קהתי",
    age: 19,
  },
  {
    firstName: "נדב",
    lastName: "קובץ",
    age: 21,
  },
  {
    firstName: "בן ציון",
    lastName: "קובריגרו",
    age: 38,
  },
  {
    firstName: "יעקב-פביאן",
    lastName: "קוזמה",
    age: 20,
    year: 1997,
  },
  {
    firstName: "גיל",
    lastName: "קוטלר",
    age: 37,
  },
  {
    firstName: "הנרי",
    lastName: "קורץ",
    age: 29,
  },
  {
    firstName: "רוני-יהודה",
    lastName: "קורקוס",
    age: 20,
  },
  {
    firstName: "יוסי",
    lastName: "קורקין",
    age: 33,
    year: 1997,
  },
  {
    firstName: "פאדי",
    lastName: "קזאמל",
    age: 19,
    year: 1997,
  },
  {
    firstName: "פריד",
    lastName: "קזאמל",
    age: 42,
  },
  {
    firstName: "תומר קידר",
    lastName: "צ'יז'יק",
    age: 21,
    year: 1997,
  },
  {
    firstName: "עלי",
    lastName: "קיס",
    age: 20,
  },
  {
    firstName: "שחר-יעקב",
    lastName: "קיסוס",
    age: 21,
    year: 1997,
  },
  {
    firstName: "חי",
    lastName: "קלומיטי",
    age: 19,
  },
  {
    firstName: "אלמוג",
    lastName: "קליין",
    age: 21,
  },
  {
    firstName: "יואל (חוליו)",
    lastName: "קלכמן",
    age: 23,
  },
  {
    firstName: "רועי",
    lastName: "קלר",
    age: 21,
    year: 1999,
  },
  {
    firstName: "רונן",
    lastName: "קמחי דוזי",
    age: 20,
    year: 1999,
  },
  {
    firstName: "שומטו",
    lastName: "קסהון",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אמיר",
    lastName: "קרא",
    age: 21,
  },
  {
    firstName: "גבריאל (גבי)",
    lastName: "קרואני",
    age: 18,
  },
  {
    firstName: "תם",
    lastName: "קרין",
    age: 20,
    year: 1996,
  },
  {
    firstName: "סעיד",
    lastName: "קשקוש",
    age: 30,
  },
  {
    firstName: "רונן",
    lastName: "ראובן",
    age: 19,
  },
  {
    firstName: "אילן",
    lastName: "רבא",
    age: 22,
  },
  {
    firstName: "בעז",
    lastName: "רביד",
    age: 27,
  },
  {
    firstName: "אידור",
    lastName: "רבינוביץ'",
    age: 20,
  },
  {
    firstName: "ויטאלי",
    lastName: "רדינסקי",
    age: 33,
    year: 1997,
  },
  {
    firstName: "ארנון",
    lastName: "רדיע",
    age: 37,
  },
  {
    firstName: "יניב",
    lastName: "רואימי",
    age: 21,
    year: 1996,
  },
  {
    firstName: "גל",
    lastName: "רודובסקי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "מרדכי (מקסי)",
    lastName: "רוזנברג",
    age: 47,
  },
  {
    firstName: "שחר",
    lastName: "רוזנברג",
    age: 20,
    year: 1997,
  },
  {
    firstName: "גיל",
    lastName: "רוזנטל",
    age: 24,
  },
  {
    firstName: "נתנאל (נתי)",
    lastName: "רוזנטל",
    age: 20,
  },
  {
    firstName: "אסף",
    lastName: "רוזנפלד",
    age: 21,
    year: 1998,
  },
  {
    firstName: "הלל-דוד",
    lastName: "רוזנר",
    age: 19,
  },
  {
    firstName: "אלעד",
    lastName: "רוטהולץ",
    age: 21,
  },
  {
    firstName: "אסף",
    lastName: "רוטנברג",
    age: 20,
    year: 1997,
  },
  {
    firstName: "רם (רמו)",
    lastName: "רוטנברג",
    age: 22,
    year: 1999,
  },
  {
    firstName: "אילן",
    lastName: "רועה",
    age: 32,
    year: 1999,
  },
  {
    firstName: "טל",
    lastName: "רז",
    age: 20,
  },
  {
    firstName: "האשם",
    lastName: "רחאל",
    age: 31,
  },
  {
    firstName: "כאמל",
    lastName: "רחאל",
    age: 27,
    year: 1997,
  },
  {
    firstName: "מאג'ד (אבו חאלד)",
    lastName: "רחאל",
    age: 35,
  },
  {
    firstName: "מנצור",
    lastName: "רחאל",
    age: 24,
  },
  {
    firstName: "יצחק",
    lastName: "רחימוב",
    age: 40,
  },
  {
    firstName: "דני (ביג'ן)",
    lastName: "רחמנו",
    age: 24,
  },
  {
    firstName: "משה (מוריס)",
    lastName: "רחמני",
    age: 46,
  },
  {
    firstName: "יובל",
    lastName: "רטיג",
    age: 18,
  },
  {
    firstName: "דניאל (דני)",
    lastName: "ריי",
    age: 19,
  },
  {
    firstName: "מנחם (מלמל)",
    lastName: "רייך",
    age: 22,
  },
  {
    firstName: "רפי",
    lastName: "רייכרט",
    age: 32,
  },
  {
    firstName: "עמוס",
    lastName: "רימון",
    age: 40,
  },
  {
    firstName: "ליאור",
    lastName: "רמון",
    age: 21,
    year: 1996,
  },
  {
    firstName: "שחר",
    lastName: "רפאלי",
    age: 21,
  },
  {
    firstName: "ניקולאי",
    lastName: "רפופורט",
    age: 24,
    year: 1998,
  },
  {
    firstName: "פיטר-פנחס",
    lastName: "רפופורט",
    age: 22,
  },
  {
    firstName: "גלעד",
    lastName: "שאול",
    age: 20,
  },
  {
    firstName: "יותם בומבון",
    lastName: "שאולי",
    age: 19,
  },
  {
    firstName: "ירון שביט",
    lastName: "רקר",
    age: 21,
  },
  {
    firstName: "נביל",
    lastName: "שבסו",
    age: 24,
  },
  {
    firstName: "ליאור",
    lastName: "שבתאי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "צפריר",
    lastName: "שובל",
    age: 22,
    year: 1997,
  },
  {
    firstName: "ערן",
    lastName: "שוהם",
    age: 21,
  },
  {
    firstName: "אושרי",
    lastName: "שוורץ",
    age: 19,
    year: 1997,
  },
  {
    firstName: "רועי",
    lastName: "שוקרון",
    age: 21,
    year: 1997,
  },
  {
    firstName: "יקיר",
    lastName: "שושי",
    age: 21,
  },
  {
    firstName: "גאלב",
    lastName: "שחיידם",
    age: 20,
  },
  {
    firstName: "מרדכי (מוטי)",
    lastName: "שטייר",
    age: 21,
  },
  {
    firstName: "מיכאל",
    lastName: "שטינלוף",
    age: 40,
  },
  {
    firstName: "עמרם",
    lastName: "שטרית",
    age: 44,
  },
  {
    firstName: "ברוך",
    lastName: "שטרן",
    age: 21,
  },
  {
    firstName: "ארז",
    lastName: "שטרק",
    age: 21,
    year: 1997,
  },
  {
    firstName: "איתמר",
    lastName: "שי",
    age: 21,
    year: 1997,
  },
  {
    firstName: "איתי",
    lastName: "שיבק",
    age: 21,
  },
  {
    firstName: "אמיר (ג'ימי)",
    lastName: "שייך",
    age: 19,
  },
  {
    firstName: "תומר",
    lastName: "שייחי",
    age: 19,
  },
  {
    firstName: "אברהם-ניסן (אבי)",
    lastName: "שכטר",
    age: 20,
  },
  {
    firstName: "ישי",
    lastName: "שכטר",
    age: 21,
    year: 1996,
  },
  {
    firstName: "יובל",
    lastName: "שלו",
    age: 19,
  },
  {
    firstName: "עומר",
    lastName: "שליט סגל",
    age: 19,
    year: 1997,
  },
  {
    firstName: "ראובן",
    lastName: "שללאשוילי",
    age: 46,
  },
  {
    firstName: "יפתח",
    lastName: "שלפוברסקי",
    age: 21,
    year: 1997,
  },
  {
    firstName: "משה",
    lastName: "שמוחה",
    age: 34,
  },
  {
    firstName: "מאיר",
    lastName: "שמול",
    age: 20,
  },
  {
    firstName: "אייל",
    lastName: "שמח",
    age: 21,
  },
  {
    firstName: "נועם",
    lastName: "שמחה",
    age: 21,
  },
  {
    firstName: "מאיר",
    lastName: "שמי",
    age: 25,
  },
  {
    firstName: "יניב",
    lastName: "שמיאל",
    age: 20,
    year: 1997,
  },
  {
    firstName: "שלום (שלוה)",
    lastName: "שמילשוילי",
    age: 20,
  },
  {
    firstName: "ערן",
    lastName: "שמיר",
    age: 22,
    year: 1997,
  },
  {
    firstName: "ידג",
    lastName: "שמעון",
    age: 21,
    year: 1997,
  },
  {
    firstName: "איל",
    lastName: "שמעוני",
    age: 21,
    year: 1997,
  },
  {
    firstName: "אלכסנדר (אליק)",
    lastName: "שניידרמן",
    age: 26,
  },
  {
    firstName: "נתאי",
    lastName: "שפטס",
    age: 23,
  },
  {
    firstName: "יואב",
    lastName: "שפיגל",
    age: 22,
  },
  {
    firstName: "יצחק-יצחקי",
    lastName: "שפירא",
    age: 21,
    year: 1996,
  },
  {
    firstName: "אורן שפר",
    age: 19,
  },
  {
    firstName: "אליעזר (אלי)",
    lastName: "שפר",
    age: 20,
  },
  {
    firstName: "מרדכי",
    lastName: "שקדי",
    age: 48,
  },
  {
    firstName: "רתם",
    lastName: "שרביט",
    age: 20,
    year: 1997,
  },
  {
    firstName: "יואב",
    lastName: "שרון",
    age: 22,
  },
  {
    firstName: "צפריר (צפי)",
    lastName: "שרוני שער",
    age: 22,
    year: 1997,
  },
  {
    firstName: "ניר-מרדכי",
    lastName: "שרייבמן",
    age: 20,
    year: 1997,
  },
  {
    firstName: "הראל",
    lastName: "שרם",
    age: 21,
  },
  {
    firstName: "גיל (גילי)",
    lastName: "שרעבי",
    age: 20,
    year: 1997,
  },
  {
    firstName: "נחמיה",
    lastName: "שרעבי",
    age: 49,
  },
  {
    firstName: "גיל-מרדכי (גילי)",
    lastName: "שרף",
    age: 19,
  },
  {
    firstName: "סעיד",
    lastName: "שרף",
    age: 33,
  },
  {
    firstName: "נתן",
    lastName: "שרפי",
    age: 19,
  },
  {
    firstName: "יניב",
    lastName: "ששון",
    age: 21,
  },
  {
    firstName: "מרדכי (מוטי)",
    lastName: "תדמור",
    age: 29,
  },
  {
    firstName: "יהודה-ליאון",
    lastName: "תובל",
    age: 40,
  },
  {
    firstName: "אסלאן",
    lastName: "תחאוחו",
    age: 21,
    year: 1996,
  },
  {
    firstName: "ראגב חסאן",
    lastName: "תחאוקי",
    age: 19,
  },
];
export default FALLEN_SOLDIERS;
