const FALLEN_SOLDIERS = [
  {
    lastName: "אבו ריש",
    firstName: "עמאד (סאמר)",
    age: 35,
    year: 1999,
  },
  {
    lastName: "אבקסיס",
    firstName: "שי",
    age: 22,
    year: 1997,
  },
  {
    lastName: "אברמזון",
    firstName: "אריה-שמעון",
    age: 22,
    year: 1997,
  },
  {
    lastName: "אדלר",
    firstName: "איתי-אבי",
    age: 20,
    year: 1997,
  },
  {
    lastName: "אזולאי",
    firstName: "אורי",
    age: 25,
    year: 1996,
  },
  {
    lastName: "אזולאי",
    firstName: "אמיל",
    age: 20,
    year: 1997,
  },
  {
    lastName: "איטח",
    firstName: "צחי",
    age: 19,
    year: 2000,
  },
  {
    lastName: "אייזן",
    firstName: "גיל",
    age: 21,
    year: 1997,
  },
  {
    lastName: "אל־קבץ",
    firstName: "עמר",
    age: 22,
    year: 1999,
  },
  {
    lastName: "אלגמיס",
    firstName: "יעקב (קובי)",
    age: 21,
    year: 1997,
  },
  {
    lastName: "אלה",
    firstName: "נחום",
    age: 19,
    year: 1998,
  },
  {
    lastName: "אליה",
    firstName: "איתמר",
    age: 21,
    year: 1997,
  },
  {
    lastName: "אלמדון",
    firstName: "אמתי",
    age: 20,
    year: 1996,
  },
  {
    lastName: "אלפר",
    firstName: "עידן",
    age: 21,
    year: 1997,
  },
  {
    lastName: "אלתר",
    firstName: "אבנר",
    age: 20,
    year: 1997,
  },
  {
    lastName: "אסולין",
    firstName: "עמית",
    age: 21,
    year: 1998,
  },
  {
    lastName: "אפנר",
    firstName: "אברהם-גד (אבי)",
    age: 21,
    year: 1997,
  },
  {
    lastName: "ארזי",
    firstName: "שגיא",
    age: 23,
    year: 1997,
  },
  {
    lastName: "אריאל",
    firstName: "ערן (ערנו)",
    age: 20,
    year: 1998,
  },
  {
    lastName: "ארמן",
    firstName: "רן-ראובן",
    age: 21,
    year: 1997,
  },
  {
    lastName: "אשד",
    firstName: "עומר",
    age: 20,
    year: 1998,
  },
  {
    lastName: "אשל",
    firstName: "רונן",
    age: 21,
    year: 1998,
  },
  {
    lastName: "בביאן",
    firstName: "אלון-אברהם חי",
    age: 21,
    year: 1997,
  },
  {
    lastName: "בוק",
    firstName: "אברהם-יעקב (אבי)",
    age: 22,
    year: 1997,
  },
  {
    lastName: "ביבס",
    firstName: "פול",
    age: 26,
    year: 1997,
  },
  {
    lastName: "ביטון",
    firstName: "אורן-אורי",
    age: 21,
    year: 1997,
  },
  {
    lastName: "ביטון",
    firstName: "משה (מושיקו)",
    age: 21,
    year: 1998,
  },
  {
    lastName: "בלדרן",
    firstName: "ניצן",
    age: 20,
    year: 1998,
  },
  {
    lastName: "בלחסן",
    firstName: "איתן",
    age: 30,
    year: 1999,
  },
  {
    lastName: "בללטי",
    firstName: "רפי (רפאל)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "בן־אריה",
    firstName: "רונן",
    age: 20,
    year: 2000,
  },
  {
    lastName: "בן חיים",
    firstName: "ניר",
    age: 20,
    year: 1997,
  },
  {
    lastName: "בן מוחא",
    firstName: "יוסף (יוסי)",
    age: 19,
    year: 1998,
  },
  {
    lastName: "בן משה",
    firstName: "אשל-אמיר",
    age: 21,
    year: 1996,
  },
  {
    lastName: "בן שם",
    firstName: "קובי",
    age: 21,
    year: 1997,
  },
  {
    lastName: "בנטוב",
    firstName: "יצחק-צחי",
    age: 28,
    year: 1997,
  },
  {
    lastName: "בסול",
    firstName: "אופיר-אשר",
    age: 21,
    year: 1997,
  },
  {
    lastName: "ברנע",
    firstName: "נועם-מיכאל",
    age: 21,
    year: 1999,
  },
  {
    lastName: "ברקוביץ",
    firstName: "שגיא (סגוש)",
    age: 22,
    year: 1997,
  },
  {
    lastName: "בשיר",
    firstName: "חוסיין",
    age: 35,
    year: 1997,
  },
  {
    lastName: "גבריאל",
    firstName: "עידן",
    age: 20,
    year: 1996,
  },
  {
    lastName: "גדעון",
    firstName: "מולטו-אשר",
    age: 21,
    year: 1997,
  },
  {
    lastName: "גדרון",
    firstName: "אבישי (שייקוש)",
    age: 19,
    year: 1997,
  },
  {
    lastName: "גואטה",
    firstName: "אייל",
    age: 21,
    year: 1999,
  },
  {
    lastName: "גוטליב",
    firstName: "מיכה (מיכי)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "גולדברג",
    firstName: "תומר",
    age: 20,
    year: 1997,
  },
  {
    lastName: "גולן",
    firstName: "אביב-ששון",
    age: 24,
    year: 1997,
  },
  {
    lastName: "גולן",
    firstName: "גיא",
    age: 21,
    year: 1997,
  },
  {
    lastName: "גונן",
    firstName: "אביב",
    age: 21,
    year: 1997,
  },
  {
    lastName: "גלזר",
    firstName: "תמיר",
    age: 24,
    year: 1997,
  },
  {
    lastName: "גנדלברג",
    firstName: "ניר-ישראל",
    age: 20,
    year: 1996,
  },
  {
    lastName: "גנזמן",
    firstName: "ולרי",
    age: 22,
    year: 1996,
  },
  {
    lastName: "גפן",
    firstName: "ידידיה",
    age: 20,
    year: 2000,
  },
  {
    lastName: "גרוסמן",
    firstName: "צבי",
    age: 22,
    year: 1997,
  },
  {
    lastName: "גרנית",
    firstName: "דוד-יעקב",
    age: 22,
    year: 1999,
  },
  {
    lastName: "גרשטיין",
    firstName: "ארז",
    age: 39,
    year: 1999,
  },
  {
    lastName: "דבירי",
    firstName: "יהונתן (יוני)",
    age: 20,
    year: 1998,
  },
  {
    lastName: "דגש",
    firstName: "מאהר",
    age: 27,
    year: 1997,
  },
  {
    lastName: "דהאן",
    firstName: "אסף",
    age: 20,
    year: 1997,
  },
  {
    lastName: "דהאן",
    firstName: "יורם-יעקב",
    age: 32,
    year: 1996,
  },
  {
    lastName: "דורון",
    firstName: "זהר",
    age: 21,
    year: 1998,
  },
  {
    lastName: "הופמן",
    firstName: "אלחנדרו-אלה",
    age: 19,
    year: 1997,
  },
  {
    lastName: "הילברג",
    firstName: "יוחנן-אברהם",
    age: 23,
    year: 1997,
  },
  {
    lastName: "הירשקוביץ",
    firstName: "דורון",
    age: 20,
    year: 1999,
  },
  {
    lastName: "הרוש",
    firstName: "משה",
    age: 23,
    year: 1996,
  },
  {
    lastName: "זהבי",
    firstName: "דן (דני)",
    age: 19,
    year: 1997,
  },
  {
    lastName: "זומרפלד",
    firstName: "זאביק",
    age: 21,
    year: 1997,
  },
  {
    lastName: "זך",
    firstName: "אוהד",
    age: 19,
    year: 1998,
  },
  {
    lastName: "זנגוויל",
    firstName: "רפאל (רפי)",
    age: 24,
    year: 2000,
  },
  {
    lastName: "זריף",
    firstName: "אורן",
    age: 21,
    year: 1997,
  },
  {
    lastName: "חוג'יראת",
    firstName: "מוחמד",
    age: 27,
    year: 1996,
  },
  {
    lastName: "חושני",
    firstName: "ישראל",
    age: 35,
    year: 1997,
  },
  {
    lastName: "חזי",
    firstName: "אבנר-כפיר",
    age: 20,
    year: 1997,
  },
  {
    lastName: "חטיב",
    firstName: "מהדי",
    age: 21,
    year: 1997,
  },
  {
    lastName: "חיון",
    firstName: "רונן (רונני)",
    age: 19,
    year: 1997,
  },
  {
    lastName: "חלפון",
    firstName: "רונן",
    age: 35,
    year: 1997,
  },
  {
    lastName: "טבי",
    firstName: "רז",
    age: 22,
    year: 1997,
  },
  {
    lastName: "טיטו",
    firstName: "לירז (רז)",
    age: 21,
    year: 1999,
  },
  {
    lastName: "טמפלהוף",
    firstName: "תדהר",
    age: 24,
    year: 2000,
  },
  {
    lastName: "יואלי",
    firstName: "אמיר",
    age: 20,
    year: 1997,
  },
  {
    lastName: "יוסיפוב",
    firstName: "רוסלן",
    age: 21,
    year: 1997,
  },
  {
    lastName: "יצחק",
    firstName: "ארז",
    age: 19,
    year: 1996,
  },
  {
    lastName: "כץ",
    firstName: "מיכאל (מיקי)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "כהן",
    firstName: "אור",
    age: 20,
    year: 1998,
  },
  {
    lastName: "כהן",
    firstName: "אייל-מיקי",
    age: 20,
    year: 1998,
  },
  {
    lastName: "כהן",
    firstName: "דותן-יצחק",
    age: 22,
    year: 1997,
  },
  {
    lastName: "כהן",
    firstName: "ירמי",
    age: 23,
    year: 1997,
  },
  {
    lastName: "כהן",
    firstName: "רונן",
    age: 20,
    year: 1997,
  },
  {
    lastName: "כיתאין",
    firstName: "תום",
    age: 21,
    year: 1997,
  },
  {
    lastName: "כלפה",
    firstName: "עמוס",
    age: 29,
    year: 1998,
  },
  {
    lastName: "לב-רן",
    firstName: "גל",
    age: 22,
    year: 1997,
  },
  {
    lastName: "לוי",
    firstName: "אבישי",
    age: 27,
    year: 1997,
  },
  {
    lastName: "לוי",
    firstName: "יוסף (יוסי)",
    age: 21,
    year: 1996,
  },
  {
    lastName: "לוי",
    firstName: "שילה",
    age: 21,
    year: 1997,
  },
  {
    lastName: "לוינס",
    firstName: "רם",
    age: 22,
    year: 1997,
  },
  {
    lastName: "לימואי",
    firstName: "אברהם (אבי)",
    age: 21,
    year: 1998,
  },
  {
    lastName: "לישצינסקי",
    firstName: "נדב",
    age: 20,
    year: 1997,
  },
  {
    lastName: "לניר",
    firstName: "דביר",
    age: 22,
    year: 1997,
  },
  {
    lastName: "לנציצקי",
    firstName: "אילן",
    age: 20,
    year: 1997,
  },
  {
    lastName: "מאיר",
    firstName: "אמיר",
    age: 19,
    year: 2000,
  },
  {
    lastName: "מועלם",
    firstName: "משה",
    age: 32,
    year: 1997,
  },
  {
    lastName: "מושל",
    firstName: "גלעד",
    age: 20,
    year: 1997,
  },
  {
    lastName: "מזומן",
    firstName: "רן",
    age: 22,
    year: 1997,
  },
  {
    lastName: "מזרחי",
    firstName: "יצחק (צחי)",
    age: 21,
    year: 1996,
  },
  {
    lastName: "מיזלס",
    firstName: "גל",
    age: 24,
    year: 1997,
  },
  {
    lastName: "מיכאילוב",
    firstName: "ולדיסלב",
    age: 22,
    year: 1997,
  },
  {
    lastName: "מינס",
    firstName: "שחר",
    age: 21,
    year: 1998,
  },
  {
    lastName: "מינץ",
    firstName: "זהר",
    age: 21,
    year: 1996,
  },
  {
    lastName: "מינקר",
    firstName: "עידן",
    age: 21,
    year: 1997,
  },
  {
    lastName: "מישייקר",
    firstName: "גלעד-משה",
    age: 20,
    year: 1997,
  },
  {
    lastName: "מלוא",
    firstName: "נדב-מנחם",
    age: 24,
    year: 1997,
  },
  {
    lastName: "מלכה גרינברג",
    firstName: "צחי",
    age: 21,
    year: 2000,
  },
  {
    lastName: "מלמד",
    firstName: "יעקב (קובי)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "מלניק",
    firstName: "ודים",
    age: 34,
    year: 1997,
  },
  {
    lastName: "ממן",
    firstName: "איתן-יעקב",
    age: 26,
    year: 1997,
  },
  {
    lastName: "נגטו",
    firstName: "משה-מולו",
    age: 23,
    year: 1999,
  },
  {
    lastName: "נחמיאס",
    firstName: "אהד-ניר",
    age: 20,
    year: 1998,
  },
  {
    lastName: "ניב",
    firstName: "ליאור",
    age: 21,
    year: 2000,
  },
  {
    lastName: "ניר",
    firstName: "יובל",
    age: 22,
    year: 1997,
  },
  {
    lastName: "סבן",
    firstName: "משה (שיקו)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "סדן",
    firstName: "ניב",
    age: 19,
    year: 1997,
  },
  {
    lastName: "סיבוני",
    firstName: "אסף-יעקב",
    age: 21,
    year: 1997,
  },
  {
    lastName: "סלם",
    firstName: "יהודה",
    age: 20,
    year: 1998,
  },
  {
    lastName: "סמואלוב",
    firstName: "אורי",
    age: 21,
    year: 1998,
  },
  {
    lastName: "עדן",
    firstName: "ישיש",
    age: 44,
    year: 1997,
  },
  {
    lastName: "עוזרי",
    firstName: "שקד",
    age: 25,
    year: 2000,
  },
  {
    lastName: "עמדי",
    firstName: "יהונתן (יוני)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "עציוני",
    firstName: "נועם",
    age: 20,
    year: 1997,
  },
  {
    lastName: "פוזנר",
    firstName: "גדעון",
    age: 22,
    year: 1997,
  },
  {
    lastName: "פיזואתי",
    firstName: "שלמה (שלומי)",
    age: 19,
    year: 1997,
  },
  {
    lastName: "פלדמן",
    firstName: "מנחם (מני)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "פסחוב",
    firstName: "ויטלי",
    age: 20,
    year: 1997,
  },
  {
    lastName: "פרומוביץ",
    firstName: "רז",
    age: 19,
    year: 1998,
  },
  {
    lastName: "פרידמן",
    firstName: "מגן",
    age: 22,
    year: 1998,
  },
  {
    lastName: "פרנס",
    firstName: "הרן-אליעזר",
    age: 21,
    year: 1997,
  },
  {
    lastName: "פרנס",
    firstName: "צור",
    age: 21,
    year: 1996,
  },
  {
    lastName: "פרץ",
    firstName: "אוריאל",
    age: 22,
    year: 1998,
  },
  {
    lastName: "פרץ",
    firstName: "ערן-חי",
    age: 21,
    year: 1997,
  },
  {
    lastName: "צופיוף הכהן",
    firstName: "ירון",
    age: 20,
    year: 1997,
  },
  {
    lastName: "צירקל",
    firstName: "יונתן",
    age: 22,
    year: 1997,
  },
  {
    lastName: "קוזמה",
    firstName: "יעקב-פביאן",
    age: 20,
    year: 1997,
  },
  {
    lastName: "קורקין",
    firstName: "יוסי",
    age: 33,
    year: 1997,
  },
  {
    lastName: "קזאמל",
    firstName: "פאדי",
    age: 19,
    year: 1997,
  },
  {
    lastName: "קידר צ'יז'יק",
    firstName: "תומר",
    age: 21,
    year: 1997,
  },
  {
    lastName: "קיסוס",
    firstName: "שחר-יעקב",
    age: 21,
    year: 1997,
  },
  {
    lastName: "קלר",
    firstName: "רועי",
    age: 21,
    year: 1999,
  },
  {
    lastName: "קמחי דוזי",
    firstName: "רונן",
    age: 20,
    year: 1999,
  },
  {
    lastName: "קסהון",
    firstName: "שומטו",
    age: 21,
    year: 1997,
  },
  {
    lastName: "קרין",
    firstName: "תם",
    age: 20,
    year: 1996,
  },
  {
    lastName: "רדינסקי",
    firstName: "ויטאלי",
    age: 33,
    year: 1997,
  },
  {
    lastName: "רואימי",
    firstName: "יניב",
    age: 21,
    year: 1996,
  },
  {
    lastName: "רודובסקי",
    firstName: "גל",
    age: 20,
    year: 1997,
  },
  {
    lastName: "רוזנברג",
    firstName: "שחר",
    age: 20,
    year: 1997,
  },
  {
    lastName: "רוזנפלד",
    firstName: "אסף",
    age: 21,
    year: 1998,
  },
  {
    lastName: "רוטנברג",
    firstName: "אסף",
    age: 20,
    year: 1997,
  },
  {
    lastName: "רוטנברג",
    firstName: "רם (רמו)",
    age: 22,
    year: 1999,
  },
  {
    lastName: "רועה",
    firstName: "אילן",
    age: 32,
    year: 1999,
  },
  {
    lastName: "רחאל",
    firstName: "כאמל",
    age: 27,
    year: 1997,
  },
  {
    lastName: "רמון",
    firstName: "ליאור",
    age: 21,
    year: 1996,
  },
  {
    lastName: "רפופורט",
    firstName: "ניקולאי",
    age: 24,
    year: 1998,
  },
  {
    lastName: "שבתאי",
    firstName: "ליאור",
    age: 20,
    year: 1997,
  },
  {
    lastName: "שובל",
    firstName: "צפריר",
    age: 22,
    year: 1997,
  },
  {
    lastName: "שוורץ",
    firstName: "אושרי",
    age: 19,
    year: 1997,
  },
  {
    lastName: "שוקרון",
    firstName: "רועי",
    age: 21,
    year: 1997,
  },
  {
    lastName: "שטרק",
    firstName: "ארז",
    age: 21,
    year: 1997,
  },
  {
    lastName: "שי",
    firstName: "איתמר",
    age: 21,
    year: 1997,
  },
  {
    lastName: "שכטר",
    firstName: "ישי",
    age: 21,
    year: 1996,
  },
  {
    lastName: "שליט סגל",
    firstName: "עומר",
    age: 19,
    year: 1997,
  },
  {
    lastName: "שלפוברסקי",
    firstName: "יפתח",
    age: 21,
    year: 1997,
  },
  {
    lastName: "שמיאל",
    firstName: "יניב",
    age: 20,
    year: 1997,
  },
  {
    lastName: "שמיר",
    firstName: "ערן",
    age: 22,
    year: 1997,
  },
  {
    lastName: "שמעון",
    firstName: "ידג",
    age: 21,
    year: 1997,
  },
  {
    lastName: "שמעוני",
    firstName: "איל",
    age: 21,
    year: 1997,
  },
  {
    lastName: "שפירא",
    firstName: "יצחק-יצחקי",
    age: 21,
    year: 1996,
  },
  {
    lastName: "שרביט",
    firstName: "רתם",
    age: 20,
    year: 1997,
  },
  {
    lastName: "שרוני שער",
    firstName: "צפריר (צפי)",
    age: 22,
    year: 1997,
  },
  {
    lastName: "שרייבמן",
    firstName: "ניר-מרדכי",
    age: 20,
    year: 1997,
  },
  {
    lastName: "שרעבי",
    firstName: "גיל (גילי)",
    age: 20,
    year: 1997,
  },
  {
    lastName: "תחאוחו",
    firstName: "אסלאן",
    age: 21,
    year: 1996,
  },
];
export default FALLEN_SOLDIERS;
